Updated package name and fixed regex issues for code_states()
globalgov/manystates pull request #44
Opened 2021-11-29 12:21 UTC by BBieri

# Description

Updated package from `{qStates}` to `{manystates}` name and fixed regex issues for `code_states()` where some country name patterns were not detected properly.

## Package

* Fixed #43 by extending the regex pattern matching process of `code_states()`
* Changed the package name from `{qStates}` to `{manystates}`

# Checklist:

- [ ] PR form
  - [ ] I have given this pull request an informative title
  - [ ] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [ ] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [ ] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [ ] Package builds on Mac
  - [ ] Package builds on Windows
  - [ ] Package builds on Linux
  - [ ] CodeCov check: Package improves or maintains good test coverage
  - [ ] CodeFactor check: Package improves or maintains good style
- [ ] Documentation
  - [ ] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [ ] Any longer functions are commented inline so that it is easier to debug in the future
  - [ ] PR description above and the NEWS.md file are aligned
  - [ ] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2021-11-30 12:42 UTC, henriquesposito requested changes
Great job @BBieri , thank you! I have requested a few more changes, but we are almost there!

2021-11-30 12:42 UTC, henriquesposito commented on NEWS.md
> +# manystates 0.0.4
Keep qStates

2021-11-30 12:42 UTC, henriquesposito commented on NEWS.md
> +* Fixed #30 by transforming date columns in manystates datasets to `messydt` class
Keep original names (i.e. qStates for consistency with previous release names)

2021-11-30 12:42 UTC, henriquesposito commented on NEWS.md
> +* Closed #31 by creating manystates website
qStates

2021-11-30 12:42 UTC, henriquesposito commented on NEWS.md
> +# manystates 0.0.3
qStates

2021-11-30 12:42 UTC, henriquesposito commented on NEWS.md
> +* Added new pull request template consistent with `{manydata}`
qData

2021-11-30 12:42 UTC, henriquesposito commented on NEWS.md
> +* Re-exported package data to reflect new testing, templates and argument changes with `export_data()` function in `{manydata}`
qData

2021-11-30 12:42 UTC, henriquesposito commented on NEWS.md
> +# manystates 0.0.2
qStates

2021-11-30 12:42 UTC, henriquesposito commented on NEWS.md
> +# manystates 0.0.1
qStates

2021-11-30 12:42 UTC, henriquesposito commented on NEWS.md
> +- Created the package structure and files using `manydata::setup_package()`
qData

2021-11-30 12:42 UTC, henriquesposito commented on NEWS.md
> +- Closed #13 by using `manydata::export_data()` and other functions from `{manydata}` to form the `states` database from:
qData

2021-11-30 12:42 UTC, henriquesposito commented on NEWS.md
> +# manystates 0.0.6
Name change is a minor increment

2021-11-30 12:42 UTC, henriquesposito commented on DESCRIPTION
> +Version: 0.0.6
minor increment

2021-11-30 12:42 UTC, henriquesposito commented on README.Rmd
> +`manystates` is a data package within the [`{manydata}` ecosystem](https://github.com/globalgov) of qPackages. It contains an ensemble of datasets currently available on states in the world, includin
change ecosystem and qPackage...
ecosytem = many universe of packages
qPackage(s) = many package(s)

2021-11-30 12:42 UTC, henriquesposito commented on README.Rmd
> +Please also check out [`{manydata}`](https://github.com/globalgov/manydata) for more information about the other packages and tools to handle data from the `{manydata}` ecosystem.
many universe of packages

2021-11-30 12:42 UTC, henriquesposito commented on README.Rmd
> +The [manydata](https://github.com/globalgov/manydata) ecosystem is aimed at collecting, connecting and correcting network data across issue-domains of global governance.
many universe of packages

2021-11-30 12:42 UTC, henriquesposito commented on README.Rmd
>  While some qPackages can and do include novel data,
many packages

2021-11-30 12:42 UTC, henriquesposito commented on README.Rmd
>  much of what they offer involves standing on the shoulders of giants.
many packages line 48

2021-11-30 12:42 UTC, henriquesposito commented on README.Rmd
>  to create a new qPackage and populate with clean, consistent global governance data.
new many packages for the universe

2021-11-30 12:42 UTC, henriquesposito commented on README.Rmd
> +[manydata](https://github.com/globalgov/manydata) includes a number of functions that make it easy
manypkgs not manydata

2021-11-30 12:42 UTC, henriquesposito commented on README.Rmd
> +If you have any other ideas about how this package or the manydata ecosystem more broadly
many universe

2021-11-30 12:42 UTC, henriquesposito commented on data-raw/states/GW/prepare-GW.R
> +# manydata and manypkgs include several other
remove repeated line

2021-11-30 12:42 UTC, henriquesposito commented on data-raw/states/ISD/prepare-ISD.R
> +# manydata and manypkgs include several other
repeated line

2021-11-30 12:42 UTC, henriquesposito commented on tests/testthat/test_ARCHIGOS.R
> +# Test if  meets the manyverse requirements
many universe of packages

2021-11-30 12:42 UTC, henriquesposito commented on tests/testthat/test_ARCHIGOS.R
> +# Test if  meets the manyverse requirements
but I like manyverse as well haha... you can leave as is for now

2021-12-01 08:45 UTC, BBieri commented on .github/CONTRIBUTING.md
> +goodpractice::gp(path = "jhollway/manystates/",
Good catch! 👍

2021-12-02 07:32 UTC, jaeltan commented on NEWS.md
> +* Updated the CSS in the package to make it consistent with other packages in the manyverse
I think to keep it consistent we can stick to the qVerse here?

2021-12-02 07:34 UTC, jaeltan commented on R/extract_vdem.R
>  #' @return A dataframe of the`[vdem]` dataset in a qVerse-consistent format.
change qVerse to many packages universe?

2021-12-02 07:34 UTC, jaeltan commented on R/extract_vdem.R
>  #' and formats them to a qVerse consistent output.
change qVerse to many packages universe?

2021-12-02 07:35 UTC, jaeltan commented on R/extract_vdem.R
>    # Step 2: Format it to a qConsistent format
change qConsistent?

2021-12-02 07:35 UTC, jaeltan commented on R/extract_vdem.R
>  #' @return A dataframe of the`[vparty]` dataset in a qVerse-consistent format.
same as above

2021-12-02 07:35 UTC, jaeltan commented on R/extract_vdem.R
>  #' a qVerse consistent dataframe.
same as above

2021-12-02 07:38 UTC, jaeltan commented on README.Rmd
> +If you have any other ideas about how this package or the manydata universe more broadly
many packages universe

2021-12-02 07:42 UTC, jaeltan commented on tests/testthat/test_ARCHIGOS.R
> +# Test if the dataset meets the many universe requirements
Question: are we using many universe or many packages universe?

2021-12-02 07:42 UTC, jaeltan commented on tests/testthat/test_ARCHIGOSgenevar.R
> +# Test if the dataset meets the many universe requirements
same question as above

2021-12-02 07:42 UTC, jaeltan commented on tests/testthat/test_COW.R
> +# Test if the dataset meets the many universe requirements
also same question as above

2021-12-02 07:42 UTC, jaeltan commented on tests/testthat/test_GW.R
> +# Test if the dataset meets the many universe requirements
same qn here

2021-12-02 07:43 UTC, jaeltan commented on tests/testthat/test_ISD.R
> +# Test if the dataset meets the many universe requirements
same question here

2021-12-02 07:44 UTC, jaeltan commented on vignettes/CShapesMaps.Rmd
> +in a way that is consistent with the manyverse with the `import_cshapes()`
I think maybe we should standardise how we refer to the 'universe' of packages?

2021-12-02 07:45 UTC, jaeltan reviewed
Hi @BBieri , great job with the PR! I didn't have much to add - just some comments on wording

2021-12-02 09:14 UTC, henriquesposito reviewed
Great job addressing the changes requested @BBieri and with the review @jaeltan ! I do not have much to add here, again, great job both!

2021-12-02 09:14 UTC, henriquesposito commented on tests/testthat/test_ARCHIGOS.R
> +# Test if the dataset meets the many universe requirements
many packages == qPackages
many packages universe == qPackage ecosystem

2021-12-02 09:14 UTC, henriquesposito commented on NEWS.md
> +* Updated the CSS in the package to make it consistent with other packages in the manyverse
Agreed

2021-12-02 09:37 UTC, henriquesposito commented on README.Rmd
> +and then you can discover, install and update various `many packages` from the console.
On the README, let's use 'many packages' with a single apostrophe, since we are nor referring to a function nor a package, not to confuse users.

2021-12-02 09:37 UTC, henriquesposito commented on README.Rmd
> +While some `many packages` can and do include novel data,
'many packages'

2021-12-02 09:37 UTC, henriquesposito commented on README.Rmd
> +much of what they offer involves standing on the shoulders of giants. `many packages` endeavour to be as transparent as possible about where data comes from,
'many packages'

2021-12-06 10:34 UTC, BBieri commented on R/extract_vdem.R
>  #' @return A dataframe of the`[vdem]` dataset in a qVerse-consistent format.
What is the issue here exactly?

2021-12-06 11:15 UTC, merged