Added datasets and updates to workflow files
globalgov/manystates pull request #53
Opened 2022-07-21 08:32 UTC by jaeltan

# Description

Major additions to data across databases, updated workflow files, and also added `network_map()` and updated `code_states()` functions.

## Package

* Closed #47 by adding vignette for `code_states()`.
   * Updated regex for `code_states()` to more accurately match and translate states' names.
* Updated workflow files to include package caching.
* Added `network_map()` function which plots geographical networks from `{migraph}` package.
* Re-rendered documentation including mreport using `messydates::mreport()`.

## Data

* Added data across databases
  * Closed #9 by adding ICOW datasets to `states` database.
  * Closed #24 by adding Economic Freedom datasets to `economics` database.
  * Closed #25 by adding Freedom House data to `regimes` database.
  * Closed #48 by adding data on states' ratification rules to `ratrules` database.
  * Closed #49 by adding Colonial Relations data from ICOW dataset to `colsrels` database.
  * Closed #50 by adding self-coded data on the latitude and longitude of state capitals as `GNEVAR_STATES` dataset in `states` database.
  * Closed #51 by adding contiguity and regions data from FAO and ICOW in `contiguity` database.
* Changed class for date variables (`Beg`) from `messydt` to `mdate` using `messydates::as_messydate()` in preparation script.

# Checklist:

- [ ] PR form
  - [ ] I have given this pull request an informative title
  - [ ] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [ ] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [ ] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [ ] Package builds on Mac
  - [ ] Package builds on Windows
  - [ ] Package builds on Linux
  - [ ] CodeCov check: Package improves or maintains good test coverage
  - [ ] CodeFactor check: Package improves or maintains good style
- [ ] Documentation
  - [ ] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [ ] Any longer functions are commented inline so that it is easier to debug in the future
  - [ ] PR description above and the NEWS.md file are aligned
  - [ ] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2022-07-25 12:39 UTC, henriquesposito requested changes
Great job Jael already, this is a big PR with lots of changes! Please let me know if you have any questions about the changes requested. Some of the comments are also for discussion and require some feedback from you. Thank you!

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/contiguity/DIRCONT/DIRCONT.bib
> +}
New line at the end

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/contiguity/DIRCONT/prepare-DIRCONT.R
> +  manydata::transmutate(Beg = messydates::as_messydate(lubridate::ym(begin)),
messydates should handle this without the need for lubridate... if it does not, maybe open an issue for it.

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/contiguity/GNEVAR_CONT/prepare-GNEVAR_CONT.R
> +GNEVAR_CONT <- as_tibble(GNEVAR_CONT) %>%
Is this a GNEVAR dataset because we are filtering some of the data?

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/leaders/Archigos_documentation.R
> +#'
line

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/leaders/Archigos_documentation.R
> +#' @description A Data Base on Leaders 1875 - 2004. A collaborative effort with Kristian Skrede Gleditsch (University of Essex, UK)
What is this file?

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/regimes/FreedomHouse1/FreedomHouse1.bib
> +
line

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/regimes/FreedomHouse2/FreedomHouse2.bib
> +
line

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/regimes/FreedomHouse1/prepare-FreedomHouse1.R
> +FreedomHouse1 <- dplyr::rename(FreedomHouse1, Label = `Country/Territory`) %>%
Why do we have 2 freedom house datasets? Perhaps we can give each a more informative name inetad of 1 and 2...

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/regimes/FreedomHouse2/prepare-FreedomHouse2.R
> +FreedomHouse2 <- tidyr::pivot_longer(FreedomHouse2,
Is this a FreedomHouse_GNEVAR?

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/regimes/FreedomHouse3/FreedomHouse3.bib
> +
line

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/regimes/FreedomHouse3/prepare-FreedomHouse3.R
> +# Note that the Freedom House dataset is comprised of three distinct Excel
FreedomHouse3? Maybe we need to document better why we have 3 different datasets here...

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/states/ICOW/ICOW.bib
> +    }
line

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/states/ICOW/prepare-ICOW.R
> +ICOW <- dplyr::as_tibble(ICOW) %>%
ICOW_GENVAR?

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/states/ISD/isd_actor.R
> +                        End = dplyrrecode(as.character(lubridate::dmy(End)), "2011-12-31" = "9999-12-31"),
messydates

2022-07-25 12:39 UTC, henriquesposito commented on data-raw/states/ISD/isd_actor.R
> +isd_actor <- subset(isd_actor, !(StatID == "DEU" & Beg == "1816-01-01"))
Are we coding the dataset from another here? If so, just add a bit more details in description/documentation.

2022-07-25 12:39 UTC, henriquesposito commented on pkgdown/_pkgdown.yml
> +  bootstrap: 5
I do not think we are using bootstrap 5 in the other packages... @jaeltan could you please take a look at that and make sure we are consistent across? Thank you.

2022-07-25 12:39 UTC, henriquesposito commented on tests/testthat/test-network_map.R
> +})
line

2022-07-26 07:49 UTC, jaeltan commented on .Rbuildignore
> +^codecov\.yml$
I think it's for the functions in the package. Some of the functions are used to scrap data that were too large to be stored in our package

2022-07-26 07:52 UTC, jaeltan commented on R/code_states.R
> +code_states <- function(v, abbrev = FALSE) {
I think that's a good idea. I don't think we have a function in manypkgs that does something similar at the moment, should I just move the function?

2022-07-26 08:08 UTC, jaeltan commented on DESCRIPTION
> +Version: 0.1.1
Changed the PR description, I think we can keep this as a patch

2022-07-26 08:23 UTC, jaeltan commented on vignettes/codestates_table.Rmd
> +title: "code_states() Regex Table"
I've added it but it doesn't look nice. Maybe that's why Bernie added it as a vignette. What do you think @henriquesposito ?

2022-07-26 08:46 UTC, jaeltan commented on R/extract_vdem.R
> +                  .data$v2paenname, .data$country_name, .data$histname,
I think if we have a vignette for this it shouldn't only be about the V-dem and V-party datasets since it is only one dataset among others that deal with regime types, and I don't think we should be giving special emphasis to something that is not actually produced by ourselves. If we have a vignette it should be how to use the data in manystates as a whole? The only reason why it's a function is because the dataset is too large to be stored in the package, so we created the option for users to access it as-needed through the function

2022-07-26 08:51 UTC, jaeltan commented on R/layout_geo.R
> +#' membership <- migraph:::membership
I think I should be able to move the 'membership' data over from `migraph` and add some documentation on how the network was created from data stored in `manyenviron`. Actually, if this function works with data in the other packages, should we consider moving it to `manydata`?

2022-07-26 08:58 UTC, jhollway commented on R/layout_geo.R
> +#' membership <- migraph:::membership
Moving it to `{manydata}` is a good idea.

2022-07-26 08:59 UTC, jhollway commented on R/extract_vdem.R
> +                  .data$v2paenname, .data$country_name, .data$histname,
I don't see the need for a separate vignette about this.

2022-07-26 09:06 UTC, jaeltan commented on data-raw/leaders/Archigos_documentation.R
> +#' @description A Data Base on Leaders 1875 - 2004. A collaborative effort with Kristian Skrede Gleditsch (University of Essex, UK)
I don't think it's useful actually. I'm going to delete it.

2022-08-02 07:13 UTC, jaeltan commented on R/manystates-ratrules.R
> +#' @format The ratrules database is a list that contains the
I've moved the ratification dataset to the `states `database

2022-08-02 07:16 UTC, jaeltan commented on data-raw/contiguity/GNEVAR_CONT/prepare-GNEVAR_CONT.R
> +GNEVAR_CONT <- as_tibble(GNEVAR_CONT) %>%
It's GNEVAR because it is handcoded and not from a currently available and public dataset. I've added a comment about the filtering, it was actually to remove the rows containing variable names that were repeated throughout the dataset when importing into R

2022-08-02 09:38 UTC, jaeltan commented on data-raw/regimes/FreedomHouse2/prepare-FreedomHouse2.R
> +FreedomHouse2 <- tidyr::pivot_longer(FreedomHouse2,
No, all 3 datasets were downloaded from the Freedom House website. Freedom House provides their data in three different files, with each dataset containing the scores (1 and 3) or status (2) of the countries/territories. Technically they can be combined into one dataset, but this makes it much larger and there will be some partial duplicates, which would make using `manydata::consolidate()` on the database difficult.

I think we have the following options:
1. Combine datasets 1 and 3, reorganize dataset 2 so that only years 1973-2001 not covered in datasets 1 and 3 are included
2. Combine all 3 datasets and remove duplicates
3. Keep the 3 datasets and rename them so that they are more informative.

What do you think @henriquesposito ?

2022-08-02 09:43 UTC, jaeltan commented on pkgdown/_pkgdown.yml
> +  bootstrap: 5
both manyenviron and manytrade use bootstrap 5.

2022-08-02 10:27 UTC, jaeltan commented on data-raw/regimes/FreedomHouse2/prepare-FreedomHouse2.R
> +FreedomHouse2 <- tidyr::pivot_longer(FreedomHouse2,
At the moment I've gone with option 1

2022-08-02 12:48 UTC, henriquesposito requested changes
Great job @jaeltan , this is a very big PR indeed and we can see how much work has gone into it already! I have requested a few more changes, please let me know if you have any questions or need my help with anything. Thank you!

2022-08-02 12:48 UTC, henriquesposito commented on R/extract_cshapes.R
> +  if (!requireNamespace("cshapes", quietly = TRUE)) {
I am not sure I like this approach of requiring packages suggested ... what do you think @jaeltan ? Maybe just add cshapes and all other necessary packages here to imports and document it properly in the roxygen documentation.

2022-08-02 12:48 UTC, henriquesposito commented on R/extract_cshapes.R
> +  if (!requireNamespace("cshapes", quietly = TRUE)) {
again

2022-08-02 12:48 UTC, henriquesposito commented on R/extract_vdem.R
> +  if (!requireNamespace("vdemdata", quietly = TRUE)) {
again...

2022-08-02 12:48 UTC, henriquesposito commented on data-raw/regimes/FreedomHouse2/prepare-FreedomHouse2.R
> +FreedomHouse2 <- tidyr::pivot_longer(FreedomHouse2,
Thank you @jaeltan for the clarifications! I am not here how to proceed here either... Before making a decision I have a few questions: Are these the same dataset just split in 3 parts because of the size? Do these have the same or different variables? Do they simply cover different periods of time? What do you think @jaeltan ?

2022-08-02 12:48 UTC, henriquesposito commented on data-raw/states/RATRULES/BSrat.csv
> +ZWE,1
line

2022-08-02 12:48 UTC, henriquesposito commented on vignettes/codestates_table.Rmd
> +title: "code_states() Regex Table"
Could you maybe return as a kable and with the explanation message? I would favor keeping this in the function rather than as a vignette as we do for some of the function in manypkgs that do use these regex tables. We need to also consider that we may move the function to manypkgs...

2022-08-03 08:55 UTC, jhollway commented on DESCRIPTION
> +    tibble,
manydata should be a Depends so that tibbles are printed nicely, consolidate and other functions are available, etc.

2022-08-03 08:56 UTC, jhollway commented on pkgdown/_pkgdown.yml
> +  bootstrap: 5
This change was undone as the layout in the function/reference page had a better layout before bootstrap 5. It was also unclear what was gained by having the more recent version.

2022-08-04 09:39 UTC, jaeltan commented on R/code_states.R
> +code_states <- function(v, abbrev = FALSE) {
Technically I think it would be possible to merge both with some tweaks, but the two functions are doing pretty different things and I think it would be confusing to merge them.

2022-08-04 09:39 UTC, jaeltan commented on pkgdown/_pkgdown.yml
> +  bootstrap: 5
Ok I've changed it back to the previous version

2022-08-04 13:17 UTC, jaeltan commented on data-raw/regimes/FreedomHouse2/prepare-FreedomHouse2.R
> +FreedomHouse2 <- tidyr::pivot_longer(FreedomHouse2,
The variables in dataset 3 are also in dataset 1, but it also contains data for years (2002-2011) that are not available in dataset 1 (from 2012). Dataset 2 is presented in a different way (by status instead of the scores, so there are much fewer variables), but the information is essentially also present in datasets 1 and 3. The main difference is that dataset 2 contains data on the status of states for years 1972 to 2001, which is not available in the other two datasets.

2022-08-05 08:29 UTC, jaeltan commented on data-raw/states/ISD/isd_actor.R
> +isd_actor <- subset(isd_actor, !(StatID == "DEU" & Beg == "1816-01-01"))
I've removed this file because it contains the same data that is already in the `ISD` dataset. The code appears to be drafts for some corrections to the state abbreviation and additions to the formatting that are not necessary.

2022-08-08 08:33 UTC, jaeltan commented on R/extract_cshapes.R
> +  # Step 0: Check that package is installed:
I've replaced the`manystates::import_cshapes() `function in `network_map()` with the original `cshapes::cshp()` function. `{cshapes}` is on CRAN, and I don't think there is anything else in the package that will result in a non-CRAN dependency for manydata.

2022-08-08 12:38 UTC, jhollway requested changes

2022-08-08 12:38 UTC, jhollway commented on NEWS.md
> +* Added data across databases
also vdemdata dependency?

2022-08-08 12:38 UTC, jhollway commented on data-raw/states/RATRULES/prepare-RATRULES.R
> +RATRULES2 <- readr::read_csv("data-raw/states/RATRULES/extra_ratifs.csv")
these 'extra' are GNEVAR additions

2022-08-08 12:38 UTC, jhollway commented on data-raw/states/Stat_Actor/stat_regex.csv
> -"1","ABK","Abkhazia","abkhaz"
Is it not useful to keep a CSV/readable version of this?

2022-08-08 12:38 UTC, jhollway commented on NEWS.md
> +# manystates 0.1.1
This is actually a pretty significant release. Maybe 0.2.0?

2022-08-08 12:38 UTC, jhollway commented on R/manystates-states.R
>  #'
Isn't R/sysdata required for country identification?

2022-08-16 10:30 UTC, henriquesposito reviewed
Thank you for all the great work Jael! I left a few more comments and suggestions. Could you please double check that the website builds properly without warnings? I think we might need to update the pkgdown.yml. Thank you!

2022-08-16 10:30 UTC, henriquesposito commented on data-raw/regimes/FHaggregate/FHaggregate.bib
> +
line

2022-08-16 10:30 UTC, henriquesposito commented on data-raw/regimes/FHaggregate/prepare-FHaggregate.R
> +# FHaggregate Preparation Script
Suggestion: maybe we should call this FreedomHouseAggregate for clarity?

2022-08-16 10:30 UTC, henriquesposito commented on data-raw/regimes/FHfull/FHfull.bib
> +
line

2022-08-16 10:30 UTC, henriquesposito commented on data-raw/regimes/FHfull/prepare-FHfull.R
> +# FHfull Preparation Script
Suggestion: maybe we call these FreedomHouseStatus and FreedomHouseScore for clarity?

2022-08-16 10:30 UTC, henriquesposito commented on data-raw/regimes/FHstatus/FHstatus.bib
> +
line

2022-08-16 10:30 UTC, henriquesposito commented on data-raw/regimes/FHstatus/prepare-FHstatus.R
> +# This is a template for importing, cleaning, and exporting data
See suggestion above...

2022-08-16 10:30 UTC, henriquesposito commented on pkgdown/_pkgdown.yml
> +      - text: code_states() regex table
Did we keep or delete this vignette? Just double checking.

2022-08-16 10:30 UTC, henriquesposito commented on pkgdown/_pkgdown.yml
> +    - network_map
Moved to manydata...

2022-08-16 12:13 UTC, henriquesposito commented on NEWS.md
> +* Closed #47 by adding vignette for `code_states()`.
We removed this vignette right?

2022-08-16 12:13 UTC, henriquesposito commented on NEWS.md
> +* Added `network_map()` function which plots geographical networks from `{migraph}` package.
Added to manydata

2022-08-16 12:35 UTC, henriquesposito approved these changes
Great job Jael! Thank you for addressing all the changes promptly, we are all good on my side. As for the dataset name changes, they are just suggestions, so you can decide if you want to change them or not before merging. Thank you!

2022-08-16 15:49 UTC, jhollway approved these changes
This looks great, @jaeltan. Quite a major (minor) release! I'd need to work with the data in it more to really check through things, so why don't you merge and then we can review it for gaps/next steps afterwards.

2022-08-17 09:13 UTC, merged